version: 2

project_name: k8x

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/shankarg87/k8x/cmd.version={{.Version}} -X github.com/shankarg87/k8x/cmd.commit={{.Commit}} -X github.com/shankarg87/k8x/cmd.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: k8x
    repository:
      owner: ai-hero
      name: homebrew-k8x
    directory: Formula
    homepage: https://github.com/shankarg87/k8x
    description: "Agentic kubectl - AI-powered Kubernetes operations"
    license: "MIT"
    test: |
      system "#{bin}/k8x --version"
    install: |
      bin.install "k8x"

nfpms:
  - id: packages
    package_name: k8x
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Shank Gan
    homepage: https://github.com/shankarg87/k8x
    maintainer: Shank Gan <shank@example.com>
    description: "Agentic kubectl - AI-powered Kubernetes operations"
    license: MIT
    formats:
      - deb
      - rpm

dockers:
  - image_templates:
      - "ghcr.io/ai-hero/k8x:{{ .Tag }}-amd64"
      - "ghcr.io/ai-hero/k8x:v{{ .Major }}-amd64"
      - "ghcr.io/ai-hero/k8x:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/ai-hero/k8x:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/ai-hero/k8x:{{ .Tag }}-arm64"
      - "ghcr.io/ai-hero/k8x:v{{ .Major }}-arm64"
      - "ghcr.io/ai-hero/k8x:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/ai-hero/k8x:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

sboms:
  - artifacts: archive
