name: Test Suite

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          cache: true

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind version

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Build k8x
        run: make build

      - name: Check if API key is available
        id: check-api-key
        env:
          # This will be empty for PR from forks
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -z "$OPENAI_API_KEY" ] && [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "API key not available for PR from fork. Running tests in skip mode."
            echo "is_api_key_available=false" >> $GITHUB_OUTPUT
          else
            echo "API key available. Running full E2E tests."
            echo "is_api_key_available=true" >> $GITHUB_OUTPUT
          fi

      - name: Run E2E tests in full mode
        if: steps.check-api-key.outputs.is_api_key_available == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: make test-e2e

      - name: Run E2E tests in skip mode
        if: steps.check-api-key.outputs.is_api_key_available == 'false'
        run: make test-e2e

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-logs
          path: |
            /tmp/k8x-e2e-test-*
            /tmp/k8x-config-*
          retention-days: 5
